# It's recommended to change every "XeraTalist" to your servers name

delay: 20 # Delay for each tab update in ticks. 1 second = 20 ticks (changing requires server restart)

tablist:
  header:
    - ""
    - "&4Xera&3Tablist"
    - ""
    - "&6This the default Tablist for XeraTablist"
    - ""
  footer:
    - ""
    - "&3%tps% tps — %players% players — %ping% ping — %uptime% uptime"
    - ""
    - "&7contact: Leee#1858"
    - "&7discussion: https://discord.gg/KgrrEQr"
    - "&7website: xera.ca"
    - "&7these are the only official xera websites and contacts."
    - ""