name: XeraTablist
version: ${project.version}
main: Xera.Tablist.XeraTablist
authors: [Nate Legault, Pistonmaster]
description: ${project.description}
softdepend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: Reload the config
    permission: xera.tablist.reload
    usage: /tabrconfig
permissions:
  xera.tablist.reload:
    description: Permission to reload XeraTablist.